-- 添加50个额外的样例产品数据
INSERT INTO products (
  name, 
  description, 
  author_id, 
  author_name, 
  price, 
  currency, 
  category, 
  image_url, 
  views, 
  likes, 
  rating, 
  tags
) VALUES 
-- DeFi Products (15个)
(
  'Solana Yield Optimizer Pro',
  'Advanced yield farming strategy optimizer for Solana ecosystem. Automatically finds highest APY opportunities across 100+ protocols with risk assessment and auto-compounding features.',
  (SELECT id FROM users LIMIT 1),
  'YieldMaster',
  89.99,
  'SOL',
  'DeFi',
  'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=400&h=300&fit=crop',
  2156,
  187,
  4.8,
  '[{"type": "crypto", "label": "DeFi"}, {"type": "ai", "label": "Automated"}, {"type": "crypto", "label": "Yield"}]'::jsonb
),
(
  'Lightning Liquidity Manager',
  'Professional liquidity management tool for Solana DEXs. Monitor impermanent loss, optimize pool positions, and maximize trading fees across multiple protocols.',
  (SELECT id FROM users LIMIT 1),
  'LiquidityPro',
  45.99,
  'SOL',
  'DeFi',
  'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=400&h=300&fit=crop',
  1834,
  156,
  4.7,
  '[{"type": "crypto", "label": "DeFi"}, {"type": "education", "label": "Trading"}, {"type": "crypto", "label": "Liquidity"}]'::jsonb
),
(
  'Cross-Chain Bridge Analytics',
  'Monitor and analyze cross-chain bridge performance, security metrics, and transaction costs. Supports 20+ major bridges with real-time alerts.',
  (SELECT id FROM users LIMIT 1),
  'BridgeWatcher',
  34.99,
  'SOL',
  'Analytics',
  'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=300&fit=crop',
  987,
  89,
  4.5,
  '[{"type": "crypto", "label": "Bridge"}, {"type": "education", "label": "Analytics"}, {"type": "crypto", "label": "Security"}]'::jsonb
),
(
  'Staking Rewards Calculator',
  'Comprehensive staking calculator for Solana validators. Compare rewards, calculate optimal delegation strategies, and track validator performance.',
  (SELECT id FROM users LIMIT 1),
  'StakeGenius',
  19.99,
  'SOL',
  'Tools',
  'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=300&fit=crop',
  1456,
  123,
  4.6,
  '[{"type": "crypto", "label": "Staking"}, {"type": "education", "label": "Calculator"}, {"type": "crypto", "label": "Solana"}]'::jsonb
),
(
  'DeFi Insurance Protocol',
  'Smart contract insurance coverage for DeFi protocols. Automated claims processing and risk assessment using AI algorithms.',
  (SELECT id FROM users LIMIT 1),
  'SafeDefi',
  199.99,
  'SOL',
  'Security',
  'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=400&h=300&fit=crop',
  567,
  67,
  4.4,
  '[{"type": "crypto", "label": "Insurance"}, {"type": "ai", "label": "Security"}, {"type": "crypto", "label": "DeFi"}]'::jsonb
),

-- AI Tools (15个)
(
  'AI Trading Signal Generator',
  'Advanced machine learning model that generates high-accuracy trading signals for cryptocurrency markets. Includes backtesting and risk management.',
  (SELECT id FROM users LIMIT 1),
  'AITrader',
  149.99,
  'SOL',
  'AI Tools',
  'https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=400&h=300&fit=crop',
  3421,
  298,
  4.9,
  '[{"type": "ai", "label": "Trading"}, {"type": "crypto", "label": "Signals"}, {"type": "ai", "label": "ML"}]'::jsonb
),
(
  'Smart Contract Code Generator',
  'AI-powered Solana smart contract generator. Write secure Rust code with built-in security patterns and gas optimization.',
  (SELECT id FROM users LIMIT 1),
  'CodeAI',
  79.99,
  'SOL',
  'AI Tools',
  'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=400&h=300&fit=crop',
  2134,
  189,
  4.7,
  '[{"type": "ai", "label": "Code Gen"}, {"type": "crypto", "label": "Smart Contracts"}, {"type": "ai", "label": "Security"}]'::jsonb
),
(
  'Crypto Sentiment Analyzer',
  'Real-time sentiment analysis for cryptocurrency markets using social media, news, and on-chain data. Predict market movements with AI.',
  (SELECT id FROM users LIMIT 1),
  'SentimentAI',
  54.99,
  'SOL',
  'AI Tools',
  'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=300&fit=crop',
  1876,
  167,
  4.6,
  '[{"type": "ai", "label": "Sentiment"}, {"type": "crypto", "label": "Analytics"}, {"type": "ai", "label": "Prediction"}]'::jsonb
),
(
  'NFT Rarity Predictor',
  'AI model that predicts NFT rarity and value based on metadata, trait analysis, and market trends. Support for major Solana NFT collections.',
  (SELECT id FROM users LIMIT 1),
  'RarityAI',
  39.99,
  'SOL',
  'AI Tools',
  'https://images.unsplash.com/photo-1617791160536-598cf32026fb?w=400&h=300&fit=crop',
  1234,
  145,
  4.5,
  '[{"type": "ai", "label": "NFT"}, {"type": "crypto", "label": "Prediction"}, {"type": "ai", "label": "Rarity"}]'::jsonb
),
(
  'Automated Market Maker Bot',
  'Intelligent AMM bot that provides liquidity on Solana DEXs. Dynamic pricing, impermanent loss protection, and yield optimization.',
  (SELECT id FROM users LIMIT 1),
  'AMMBot',
  299.99,
  'SOL',
  'AI Tools',
  'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=300&fit=crop',
  876,
  98,
  4.8,
  '[{"type": "ai", "label": "Bot"}, {"type": "crypto", "label": "AMM"}, {"type": "crypto", "label": "Liquidity"}]'::jsonb
),

-- Educational Content (10个)
(
  'Solana Developer Bootcamp',
  'Complete 12-week bootcamp for Solana blockchain development. Includes Rust programming, Anchor framework, and real project deployment.',
  (SELECT id FROM users LIMIT 1),
  'SolanaAcademy',
  499.99,
  'SOL',
  'Education',
  'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=400&h=300&fit=crop',
  5432,
  567,
  4.9,
  '[{"type": "education", "label": "Bootcamp"}, {"type": "crypto", "label": "Solana"}, {"type": "education", "label": "Programming"}]'::jsonb
),
(
  'DeFi Security Masterclass',
  'Advanced course on DeFi security best practices. Learn about common vulnerabilities, audit techniques, and secure coding patterns.',
  (SELECT id FROM users LIMIT 1),
  'SecurityGuru',
  199.99,
  'SOL',
  'Education',
  'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400&h=300&fit=crop',
  2876,
  234,
  4.8,
  '[{"type": "education", "label": "Security"}, {"type": "crypto", "label": "DeFi"}, {"type": "education", "label": "Audit"}]'::jsonb
),
(
  'Crypto Economics 101',
  'Comprehensive guide to cryptocurrency economics, tokenomics, and blockchain game theory. Perfect for beginners and investors.',
  (SELECT id FROM users LIMIT 1),
  'EconTeacher',
  89.99,
  'SOL',
  'Education',
  'https://images.unsplash.com/photo-1434626881859-194d67b2b86f?w=400&h=300&fit=crop',
  3456,
  345,
  4.7,
  '[{"type": "education", "label": "Economics"}, {"type": "crypto", "label": "Tokenomics"}, {"type": "education", "label": "Theory"}]'::jsonb
),
(
  'NFT Creation Workshop',
  'Step-by-step guide to creating, minting, and marketing NFTs on Solana. Includes art techniques, metadata standards, and marketplace strategies.',
  (SELECT id FROM users LIMIT 1),
  'NFTCreator',
  69.99,
  'SOL',
  'Education',
  'https://images.unsplash.com/photo-1617791160536-598cf32026fb?w=400&h=300&fit=crop',
  1987,
  198,
  4.6,
  '[{"type": "education", "label": "NFT"}, {"type": "crypto", "label": "Creation"}, {"type": "education", "label": "Marketing"}]'::jsonb
),
(
  'Yield Farming Strategies Guide',
  'Professional guide to yield farming across multiple chains. Risk assessment, strategy optimization, and tax implications.',
  (SELECT id FROM users LIMIT 1),
  'YieldExpert',
  45.99,
  'SOL',
  'Education',
  'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=400&h=300&fit=crop',
  1654,
  178,
  4.5,
  '[{"type": "education", "label": "Yield"}, {"type": "crypto", "label": "Farming"}, {"type": "education", "label": "Strategy"}]'::jsonb
),

-- Development Tools (10个)
(
  'Solana Testing Framework',
  'Comprehensive testing framework for Solana programs. Unit tests, integration tests, and simulation tools with CI/CD integration.',
  (SELECT id FROM users LIMIT 1),
  'TestDev',
  159.99,
  'SOL',
  'Tools',
  'https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=400&h=300&fit=crop',
  1432,
  156,
  4.8,
  '[{"type": "education", "label": "Testing"}, {"type": "crypto", "label": "Solana"}, {"type": "education", "label": "Framework"}]'::jsonb
),
(
  'Web3 UI Component Library',
  'Beautiful React components for Web3 applications. Wallet connectors, transaction buttons, and blockchain data displays.',
  (SELECT id FROM users LIMIT 1),
  'UIBuilder',
  79.99,
  'SOL',
  'Templates',
  'https://images.unsplash.com/photo-1611095790444-1dfa35800054?w=400&h=300&fit=crop',
  2145,
  187,
  4.7,
  '[{"type": "education", "label": "UI"}, {"type": "crypto", "label": "Web3"}, {"type": "education", "label": "Components"}]'::jsonb
),
(
  'Solana RPC Dashboard',
  'Monitor Solana RPC performance, track API calls, and optimize node selection. Essential tool for dApp developers.',
  (SELECT id FROM users LIMIT 1),
  'RPCMonitor',
  34.99,
  'SOL',
  'Tools',
  'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=300&fit=crop',
  987,
  89,
  4.6,
  '[{"type": "education", "label": "RPC"}, {"type": "crypto", "label": "Infrastructure"}, {"type": "education", "label": "Monitoring"}]'::jsonb
),
(
  'Smart Contract Deployer',
  'One-click smart contract deployment tool for Solana. Version management, upgrade paths, and multi-environment support.',
  (SELECT id FROM users LIMIT 1),
  'DeployMaster',
  49.99,
  'SOL',
  'Tools',
  'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=300&fit=crop',
  1234,
  112,
  4.5,
  '[{"type": "education", "label": "Deployment"}, {"type": "crypto", "label": "Smart Contracts"}, {"type": "education", "label": "DevOps"}]'::jsonb
),
(
  'Blockchain Data Indexer',
  'High-performance blockchain data indexing service. Real-time data processing with GraphQL API and custom analytics.',
  (SELECT id FROM users LIMIT 1),
  'DataIndexer',
  199.99,
  'SOL',
  'Analytics',
  'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=300&fit=crop',
  876,
  78,
  4.7,
  '[{"type": "education", "label": "Indexing"}, {"type": "crypto", "label": "Data"}, {"type": "ai", "label": "Analytics"}]'::jsonb
),

-- 创新产品类别 (10个)
(
  'Solana Mobile dApp Kit',
  'Complete development kit for Solana mobile applications. Includes wallet integration, mobile-optimized components, and push notifications.',
  (SELECT id FROM users LIMIT 1),
  'MobileDev',
  129.99,
  'SOL',
  'Templates',
  'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400&h=300&fit=crop',
  1567,
  134,
  4.6,
  '[{"type": "crypto", "label": "Mobile"}, {"type": "education", "label": "Development"}, {"type": "crypto", "label": "dApp"}]'::jsonb
),
(
  'GameFi Token Economics',
  'Complete tokenomics design framework for blockchain games. Balanced economy models, player incentives, and sustainability metrics.',
  (SELECT id FROM users LIMIT 1),
  'GameEcon',
  89.99,
  'SOL',
  'Gaming',
  'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=400&h=300&fit=crop',
  2234,
  198,
  4.8,
  '[{"type": "crypto", "label": "Gaming"}, {"type": "education", "label": "Tokenomics"}, {"type": "crypto", "label": "GameFi"}]'::jsonb
),
(
  'Social Token Platform',
  'Launch and manage social tokens for creators and communities. Fan engagement, governance features, and monetization tools.',
  (SELECT id FROM users LIMIT 1),
  'SocialToken',
  149.99,
  'SOL',
  'Social',
  'https://images.unsplash.com/photo-1611095790444-1dfa35800054?w=400&h=300&fit=crop',
  1876,
  167,
  4.5,
  '[{"type": "crypto", "label": "Social"}, {"type": "education", "label": "Creator"}, {"type": "crypto", "label": "Token"}]'::jsonb
),
(
  'DAO Governance Toolkit',
  'Complete governance solution for DAOs. Proposal management, voting mechanisms, treasury management, and member onboarding.',
  (SELECT id FROM users LIMIT 1),
  'DAOBuilder',
  199.99,
  'SOL',
  'Governance',
  'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=400&h=300&fit=crop',
  1234,
  145,
  4.7,
  '[{"type": "crypto", "label": "DAO"}, {"type": "education", "label": "Governance"}, {"type": "crypto", "label": "Democracy"}]'::jsonb
),
(
  'Carbon Credit Marketplace',
  'Blockchain-based carbon credit trading platform. Verified credits, automated offsetting, and sustainability tracking for businesses.',
  (SELECT id FROM users LIMIT 1),
  'GreenChain',
  299.99,
  'SOL',
  'Sustainability',
  'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400&h=300&fit=crop',
  789,
  89,
  4.4,
  '[{"type": "crypto", "label": "Green"}, {"type": "education", "label": "Carbon"}, {"type": "crypto", "label": "ESG"}]'::jsonb
);

-- 更新产品统计数据的函数调用示例
-- 这些可以用于模拟真实的用户互动
UPDATE products SET views = views + FLOOR(RANDOM() * 100) WHERE views > 0;
UPDATE products SET likes = likes + FLOOR(RANDOM() * 20) WHERE likes > 0;